#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 11 16:28:29 2019

@author: denisebaker
"""

num = int(input('Enter a number:  '))

if num % 2 == 0:
    print('even')
    
else:
    print('odd')