#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 11 16:11:36 2019

@author: denisebaker
"""

name = input('Please enter your name:  ')
print('Your name is ' + name)

age = int(input('Please enter your age:  '))
age += 100
print(age)
    